### ISSUE TITLE
Why is click being called three times?

### ISSUE THREAD

**Issue by shard2001** [jquery/jquery.com#216] opened 2021-03-04 15:33 UTC
http://jsfiddle.net/2ra0h9ns/3/

```
 <div><input type="radio" id='a' name="type" checked="checked" value="guest" onclick="alert('a')"/><label>A</label></div>
<div><input type="radio" name="type" value="guest" onclick="alert('b')"/><label>B</label></div>

```
$("#a").click()

**Comment by dmethvin** [comment] 2021-03-04 15:56
Duplicate of #4638

**Closed by dmethvin** 2021-03-04 15:56 UTC
