### ISSUE TITLE
the number of the latest version is wrong

### ISSUE THREAD

**Issue by IsibisiDev** [jquery/jquery.com#187] opened 2019-04-10 22:28 UTC
the number of the last version of jquery on the home and in the page / download is wrong, instead of 3.4.0 there is 3.0.0

**Comment by timmywil** [comment] 2019-04-10 23:26
The changes were committed and I created a tag, but it seems the deployment didn't finish. I think we have Jenkins do this, but there are others more familiar with that process.

**Comment by mgol** [comment] 2019-04-11 09:54
> instead of 3.4.0 there is 3.0.0

I think you meant `3.3.0`? That's what I was seeing as well.

The page should be up to date now. It might have been caused by a tag name not starting with `v`: namely, `3.0.25` instead of the expected `v3.0.25`.

Thanks for reporting!

**Closed by mgol** 2019-04-11 09:54 UTC
