### ISSUE TITLE
Certificate chain issue *.jquery.com

### ISSUE THREAD

**Issue by IvandeJong** [jquery/jquery.com#204] opened 2020-06-02 09:04 UTC
There seems to be an issue in the*.jquery.com certificate.
Ssl labs:
https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com&latest
![image](https://user-images.githubusercontent.com/9018471/83501711-cee4d200-a4c0-11ea-977d-2b22f2967e0b.png)

Most browser dont block this but some firewalls (including our fortigate block  request when one of the certificate chain paths is invalid)

**Comment by mgol** [comment] 2020-06-02 11:42
Duplicate of https://github.com/jquery/codeorigin.jquery.com/issues/59.

**Closed by mgol** 2020-06-02 11:42 UTC
