### ISSUE TITLE
SSL issue on code.jquery.com

### ISSUE THREAD

**Issue by JasonGoemaat** [jquery/jquery.com#172] opened 2018-04-19 20:54 UTC
Some websites were breaking for me and I tracked it down to this.  The SSL cert is coming back ssl.hwcdn.net so my browsers won't load jquery from the site:

[https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com](https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com)

**Comment by dmethvin** [comment] 2018-04-19 20:55
Duplicate of https://github.com/jquery/codeorigin.jquery.com/issues/34

**Closed by dmethvin** 2018-04-19 20:55 UTC
