### ISSUE TITLE
Misleading footprint description in homepage

### ISSUE THREAD

**Issue by Chealer** [jquery/jquery.com#149] opened 2016-10-10 01:44 UTC
The homepage contains:
>Lightweight Footprint

>Only 32kB minified and gzipped. Can also be included as an AMD module

Including a compressed size while not including an uncompressed size implies that download time matters more than evaluation time. Yet, just evaluating jQuery Core 1.10 on a fairly performant PC (2-year-old AMD A8-5600K APU) takes roughly 46 ms.

I have included jQuery Core by default in an internal application without realizing I was adding such a footprint to it, after having considered performance. I reckon I might have been ignorant/careless then, but I thought the main impact would be the time taken to fetch jQuery (HTTP). And since our server is local, that was a non-issue. I absolutely did not see script evaluation time.

However, looking at the quote above, I can understand why someone would only think about download time. While download time is indeed much more important on first load (although it has been pointed out that using CDN-s, even the first load may not require downloading jQuery), in the end, evaluation is much more important, at least in most environments.

I do not regret having included jQuery Core, but in some contexts, evaluation time will make the difference between including and avoiding. The current description misleads by:

1. Implying that jQuery Core's download costs more than evaluation, which is generally wrong
2. In general, implying that the download costs of JavaScript code are greater than evaluation costs, which is also generally wrong and even more misleading

If we want to quantify footprint by size, we should make the standard or minified size (probably the latter indeed) at least as prominent as the gzipped size. My recommendation would be to replace the gzipped size with the uncompressed minified size.

**Comment by timmywil** [comment] 2016-10-10 13:47
Duplicate of #148. Please do not open another issue and continue discussion in the original ticket. I believe @dmethvin's answer was sufficient to close the ticket because we will not be making changes to the homepage. There seems to be some confusion about the impact of jQuery evaluation. 46ms is pretty good, but even if it's not, unminified size is irrelevant.

**Closed by timmywil** 2016-10-10 13:47 UTC

**Comment by Chealer** [comment] 2016-10-16 17:49
Timmy, I asked Dave in ticket #148 why he closed the ticket and no one has replied since. I cannot discuss alone.

Why would we not change the homepage?

I am not sure what your point is. I never claimed that 46 ms was not "good", I merely pointed out that in some contexts, evaluation time will make the difference between including and avoiding. This will remain true no matter the evaluation time. I also fail to understand why you are discussing the unminified size.

**Comment by timmywil** [comment] 2016-10-16 20:28
I meant uncompressed, or minified. I understand your point that evaluation matters. However, you want us to put more emphasis on the evaluation time of jQuery, but you admit that the evaluation time does not seem to be a problem. I do not think the evaluation time of jQuery is the bottleneck for any application, therefore I disagree it has any bearing on the decision to include it. The resolution of the ticket is that no changes will be made.

**Comment by dmethvin** [comment] 2016-10-18 22:19
@Chealer I think your points about parse time are valid but they are not points that I think should be addressed on the home page for jQuery. Developers need to know a lot of things that will not be explained on the jQuery home page. One thing that people often want to know is *roughly*, "how big is this library"? That is why we put it there.

**Comment by Chealer** [comment] 2017-10-07 15:54
@timmywil , I did not "admit that the evaluation time does not seem to be a problem". I just said I do not regret the decision I made to include jQuery Core in one specific case. I could have regretted including in a different context.

And the fact (true or not) that jQuery Core's evaluation time would not be the bottleneck for any application does not mean it should have no influence on the decision to include it.

**Comment by Chealer** [comment] 2017-10-07 16:05
@dmethvin , this ticket does not ask to address any point about parse time on the home page for jQuery.

Nor did I ever ask to remove any information about the library's size.

All I asked was to (quoting myself) "make the standard or minified size (probably the latter indeed) at least as prominent as the gzipped size".

**Comment by Chealer** [comment] 2018-07-01 14:20
The issue persists; thanks for reopening.
